server:
  port: 8888

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: git@github.com:IlianMetina/BankApp-Config.git
          default-label: master
#          clone-on-start: true
#          username: ${GIT_USERNAME}
#          password: ${GIT_TOKEN}
